### PR TITLE
feat: collab entities in protobuf format

### PR DESCRIPTION
**Pull request by khorshuheng**
Currently, we are using bincode to serialize and deserialize Rust struct that needs to be transferred over the network. In order to achieve better backward compatibility and manage schema changes, we will be migrating to protobuf for serialization.

We will start with this PR, that creates the protobuf requires for the serialization/deserialization of these Rust struct:
- [EncodedCollab](https://github.com/AppFlowy-IO/AppFlowy-Collab/blob/main/collab/src/entity.rs#L6)
- [PubSubMessage](https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/main/libs/collab-stream/src/pubsub.rs#L57)
- [CollabParams](https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/main/libs/database-entity/src/dto.rs#L65)
- [CreateCollabParams](https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/main/libs/database-entity/src/dto.rs#L17)
- [BatchCreateCollabParams](https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/main/libs/database-entity/src/dto.rs#L118)
- [CollabUpdateEvent](https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/main/libs/collab-stream/src/model.rs#L302)
- [RealtimeMessage](https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/main/libs/collab-rt-entity/src/message.rs#L38)

Comments have been added to the protobuf based on my current understanding, which might not be accurate. Hence, review is needed to make sure that the comments are not misleading.

We will follow up with subsequent PRs that update the serialization and deserialization of the above structs.

### CODE REVIEW

**Comment by khorshuheng** [comment]
The test failure is likely due to the regex_automata downgrade: 
```
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "8263075bb86c5a1b1427b5ae862e8889656f126e9f77c484496e8b47cf5c5558"
dependencies = [
 "regex-automata",
 "regex-automata 0.1.10",
]
```
Going to find out how to resolve this.

**Comment by khorshuheng** [comment]
> The test failure is likely due to the regex_automata downgrade:
> 
> ```
> source = "registry+https://github.com/rust-lang/crates.io-index"
> checksum = "8263075bb86c5a1b1427b5ae862e8889656f126e9f77c484496e8b47cf5c5558"
> dependencies = [
>  "regex-automata",
>  "regex-automata 0.1.10",
> ]
> ```
> 
> Going to find out how to resolve this. This is due to introduction of the `prost-build` build dependencies.

Updated tracing-subscriber version due to: https://github.com/tokio-rs/tracing/issues/2573

**Comment by khorshuheng** [comment]
Added protobuf definition for CreateCollabParams and BatchCreateCollabParams.

**Comment by khorshuheng** [comment]
Just realized that we could potentially simplified this via: https://github.com/tokio-rs/prost?tab=readme-ov-file#tag-inference-for-existing-types . Exploring this now.

**Comment by khorshuheng** [comment]
CollabSnapshot is being called in get_last_snapshot etc, but those methods are not currently in use anywhere in AppFlowy. In other word, although we are serializing this struct, it is never deserialized back again. Is this intended? @appflowy

**Comment by khorshuheng** [comment]
@Horusiath  @appflowy Any suggestion as to whether the generated code should be checked in? Right now we have both cases in different libraries and repositories across the org.

**Comment by Horusiath** [comment]
@khorshuheng personally I'm not a fan of checking in the code - it obscures the PR review - but it should be part of the build step.

**Comment by appflowy** [comment]
It needs to test it can be integrate with frontend application. Since it involves build.rs

**Comment by khorshuheng** [comment]
> It needs to test it can be integrate with frontend application. Since it involves build.rs

I will test this via https://github.com/AppFlowy-IO/AppFlowy/pull/5745

**Pull request merged**
